### PR TITLE
Review interval serializer

### PR DESCRIPTION
**Pull request by maarzt**
Hello @kozusznik, I reviewed the code "a bit". And made I lots of changes. The main purpose is to increase code readability.

The split into scijava-parallel and scijava-parallel-imagej-server is confusing. All this code should be in scijava-parallel. We can break the dependency to imagej-server by a better approach. scijava-parallel-imagej-server only depends on ```ObjectMapperModifier```and ```SerializerModifier```. We can put those two classes in a separate maven project (maybe named imagej-server-json).
imagej-server and scijava-parallel would both have imagej-server-json as dependency.

### CODE REVIEW

**Comment by kozusznik** [comment]
> Hello @kozusznik, I reviewed the code "a bit". And made I lots of changes. The main purpose is to increase code readability.
> 
> The split into scijava-parallel and scijava-parallel-imagej-server is confusing. All this code should be in scijava-parallel. We can break the dependency to imagej-server by a better approach. scijava-parallel-imagej-server only depends on `ObjectMapperModifier`and `SerializerModifier`. We can put those two classes in a separate maven project (maybe named imagej-server-json).
> imagej-server and scijava-parallel would both have imagej-server-json as dependency.

**Comment by kozusznik** [comment]
I have revised suggested changes and I like it.
A primary motivation for a separate project scijava-parallel-imagej-server is not existing dependency to ImageJ server but I would leave only API in scijava-parallel. On the other hand, I could move everything back to the scijava and do the separation in the future.

**Comment by maarzt** [comment]
I was reviewing this code, with the goal of converting it into production code. That was a too early, as you guys correctly pointed out during the discussion. The code stay like it is for testing the first use cases.

When this code is turned into production we might address the following:
* Routines.runWithExceptionHandling and Routines.supplyWithExceptionHandling don't need the log and action parameters.
* ParallelizationParadigmConverterFactory needs to be refactored such that it becomes very simple to implement a plugin like IntervalImageJServerConverterFactory.
* ParallelWorker probably don't need the importData & exportData methods.
* ImageJServerRunner doesn't need a separate start method, it could be started in the constructor directly?

**Comment by kozusznik** [comment]
I copied all source codes back to the project scijava-parallel (with their commit history). It is in a branch https://github.com/PetrBainar/scijava-parallel/tree/integrationCodesFromIJServer.

**Pull request closed without merging**
